wandb_version: 1

seed:
  desc: null
  value: 42
n_hidden_layers:
  desc: null
  value: 8
n_hidden_neurons:
  desc: null
  value: 256
max_epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
wandb:
  desc: null
  value:
    entity: agrawalp
    project: PCAPRO
    group: Development
    job_type: Training
    tags:
    - development
    _service_wait: '300'
    notes: Mapping function.
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725444499.677749
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 2
      - 7
      - 13
      - 15
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: train_RAE_step
      5: 1
      6:
      - 1
    - 1: train_MAE_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid_loss
      5: 1
      6:
      - 1
    - 1: valid_MAE
      5: 1
      6:
      - 1
    - 1: valid_MAE_0
      5: 1
      6:
      - 1
    - 1: valid_MAE_1
      5: 1
      6:
      - 1
    - 1: valid_MAE_2
      5: 1
      6:
      - 1
    - 1: valid_MAE_3
      5: 1
      6:
      - 1
    - 1: valid_MAE_4
      5: 1
      6:
      - 1
    - 1: valid_MAE_5
      5: 1
      6:
      - 1
    - 1: valid_MAE_6
      5: 1
      6:
      - 1
    - 1: valid_MAE_7
      5: 1
      6:
      - 1
    - 1: valid_RAE
      5: 1
      6:
      - 1
    - 1: valid_RAE_0
      5: 1
      6:
      - 1
    - 1: valid_RAE_1
      5: 1
      6:
      - 1
    - 1: valid_RAE_2
      5: 1
      6:
      - 1
    - 1: valid_RAE_3
      5: 1
      6:
      - 1
    - 1: valid_RAE_4
      5: 1
      6:
      - 1
    - 1: valid_RAE_5
      5: 1
      6:
      - 1
    - 1: valid_RAE_6
      5: 1
      6:
      - 1
    - 1: valid_RAE_7
      5: 1
      6:
      - 1
    - 1: valid_CorrCoeff
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_RAE_epoch
      5: 1
      6:
      - 1
    - 1: train_MAE_epoch
      5: 1
      6:
      - 1
