wandb_version: 1

seed:
  desc: null
  value: 42
n_hidden_layers:
  desc: null
  value: 8
n_hidden_neurons:
  desc: null
  value: 256
max_epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.0001
wandb:
  desc: null
  value:
    entity: agrawalp
    project: PCAPRO
    group: Development
    job_type: Training
    tags:
    - development
    _service_wait: '300'
    notes: Mapping function.
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725443084.107911
    t:
      1:
      - 1
      - 9
      - 55
      - 103
      2:
      - 1
      - 9
      - 55
      - 103
      3:
      - 7
      - 13
      - 15
      - 16
      - 23
      4: 3.9.18
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
